import createjs from "../../createjs/createjs";

(function() {
	"use strict";

	function CacheManager() {
		this.staticFrames=60;
		this.movieClipStaticFrames=2;
		this.maxCachePixels=2048*2048;
		this.maxCacheDimension=4096;
		this.cacheObjectCount=0;
		this._matrix=new createjs.Matrix2D();
	}
	var p=CacheManager.prototype;

	p.update=function(list,changed) {
		var i,o;
		for (i=0; i<list.length; i++) {
			o=list[i];
			if (changed[o.id]) {
				this.release(o);
				for (var parent=o.parent; parent; parent=parent.parent) { this.release(parent); parent._staticFrames=0; }
				o._staticFrames=0;
			} else { o._staticFrames=(o._staticFrames || 0)+1; }
		}
		for (i=list.length-1; i>=0; i--) {
			o=list[i];
			if (!o._autoCache && this._eligible(o)) { this.create(o); }
		}
		this.cacheObjectCount=0;
		for (i=0; i<list.length; i++) { if (list[i]._autoCache) { this.cacheObjectCount++; } }
	};

	p._eligible=function(o) {
		if (!o.visible || o.alpha <= 0 || o.bitmapCache || o.mask || o.filters || o.compositeOperation || o.shadow || o.tweenjs_count) { return false; }
		if (o._hasMouseEventListener && o._hasMouseEventListener()) { return false; }
		for (var ancestor=o.parent; ancestor; ancestor=ancestor.parent) { if (ancestor._autoCache) { return false; } }
		var isMovieClip=createjs.MovieClip && o instanceof createjs.MovieClip;
		if (isMovieClip && !o.paused) { return false; }
		var isContainer=createjs.Container && o instanceof createjs.Container;
		var threshold=isMovieClip ? this.movieClipStaticFrames : this.staticFrames;
		if ((o._staticFrames || 0) < threshold) { return false; }
		if (isContainer) {
			if (!o.children.length || o === o.stage) { return false; }
			for (var i=0; i<o.children.length; i++) {
				var child=o.children[i];
				if (child.mask || child.filters || child.compositeOperation || child.tweenjs_count ||
					(createjs.MovieClip && child instanceof createjs.MovieClip && !child.paused)) { return false; }
			}
		} else if (!(createjs.Shape && o instanceof createjs.Shape) && !(createjs.Text && o instanceof createjs.Text)) { return false; }
		var bounds=o.getBounds && o.getBounds(), scale=this._getScale(o);
		var padding=o._getPhase2BoundsPadding ? o._getPhase2BoundsPadding() : 1;
		var width=bounds ? bounds.width+padding*2 : 0, height=bounds ? bounds.height+padding*2 : 0;
		return !!(bounds && bounds.width > 0 && bounds.height > 0 && width*scale <= this.maxCacheDimension &&
			height*scale <= this.maxCacheDimension && width*height*scale*scale <= this.maxCachePixels);
	};

	p._getScale=function(o) {
		var matrix=o.getConcatenatedMatrix(this._matrix);
		// Largest singular value of the 2x2 transform, which also handles skew
		// without under-sampling the generated bitmap.
		var sum=matrix.a*matrix.a+matrix.b*matrix.b+matrix.c*matrix.c+matrix.d*matrix.d;
		var determinant=matrix.a*matrix.d-matrix.b*matrix.c;
		var discriminant=Math.max(0,sum*sum-4*determinant*determinant);
		var scale=Math.sqrt((sum+Math.sqrt(discriminant))/2);
		// Cache at the final device-pixel density. _eligible() rejects surfaces
		// that would exceed maxCachePixels instead of lowering quality.
		return Math.max(1,scale);
	};

	p.create=function(o) {
		var bounds=o.getBounds();
		if (!bounds) { return false; }
		var scale=this._getScale(o);
		var padding=o._getPhase2BoundsPadding ? o._getPhase2BoundsPadding() : 1;
		var cache=o.bitmapCache=new createjs.BitmapCache();
		cache._autoGenerated=true;
		cache.define(o,bounds.x-padding,bounds.y-padding,bounds.width+padding*2,bounds.height+padding*2,scale);
		o._autoCache=true;
		if (o.children) { this._releaseDescendants(o); }
		return true;
	};

	p._releaseDescendants=function(container) {
		for (var i=0; i<container.children.length; i++) {
			var child=container.children[i];
			this.release(child);
			if (child.children) { this._releaseDescendants(child); }
		}
	};

	p.release=function(o) {
		if (!o || !o._autoCache) { return; }
		if (o.bitmapCache && o.bitmapCache._autoGenerated) { o.bitmapCache.release(); o.bitmapCache=undefined; }
		o._autoCache=false;
	};

	createjs.CacheManager=CacheManager;
}());
