import "../createjs/utils/extend.js"
import "../createjs/utils/promote.js"
import "../createjs/utils/indexOf.js"
import "./utils/UID.js"
import "../createjs/utils/deprecate.js"
import "../createjs/events/Event.js"
import "../createjs/events/EventDispatcher.js"
import "../createjs/utils/Ticker.js"
import "./events/MouseEvent.js"
import "./geom/Matrix2D.js"
import "./geom/DisplayProps.js"
import "./geom/Point.js"
import "./geom/Rectangle.js"
import "./utils/Performance.js"
import "./display/Shadow.js"
import "./display/SpriteSheet.js"
import "./display/Graphics.js"
import "./display/DisplayObject.js"
import "./display/Container.js"
import "./display/Stage.js"
import "./display/Bitmap.js"
import "./display/Sprite.js"
import "./display/Shape.js"
import "./display/Text.js"
import "./display/BitmapText.js"
import "./display/MovieClip.js"
import "./utils/SpriteSheetUtils.js"
import "./utils/SpriteSheetBuilder.js"
import "./filters/Filter.js"
import "./filters/BitmapCache.js"
import "./filters/BlurFilter.js"
import "./filters/AlphaMapFilter.js"
import "./filters/AlphaMaskFilter.js"
import "./filters/ColorFilter.js"
import "./filters/ColorMatrix.js"
import "./filters/ColorMatrixFilter.js"
import "./render/DirtyRegionManager.js"
import "./render/CacheManager.js"
import "./render/BitmapBatchRenderer.js"
import "./ui/Touch.js"
import "./ui/ButtonHelper.js"

import createjs from "../createjs/createjs.js"

createjs.globalDispatcher = new createjs.EventDispatcher()

export default createjs
